[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "8731693ea495ec92614ea8a5da62f8e66909f0c1"
libc = "glibc"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "fa64c50e5729c85ccc5148ecface36bc77d0434c27c9091ce9d255ce448a0df0"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v9.1.0%2B5/ElectronJS-9.1.0+5-x86_64-linux-gnu.tar.gz"
[[electronjs_app]]
arch = "aarch64"
git-tree-sha1 = "bf8267793953d41b83f2b9bfb4209fe2547b0e33"
libc = "glibc"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "e191a235a8f7760ffb8d7e9816f063e36b0710494bc7f08fa27d5a7a2353b723"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v9.1.0%2B5/ElectronJS-9.1.0+5-aarch64-linux-gnu.tar.gz"
[[electronjs_app]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "54c760bb0118f54f54fbf7120d22057dbb179839"
libc = "glibc"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "e314374eba0491a813f5d0e108e525dc1944c4835a8e0eca17d44817a8323cc4"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v9.1.0%2B5/ElectronJS-9.1.0+5-armv7l-linux-gnueabihf.tar.gz"
[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "8731693ea495ec92614ea8a5da62f8e66909f0c1"
libc = "musl"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "3237ce8b2fcb7c9424584ba3f7af3e82c8375502eedd9339823a28c094f6a74e"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v9.1.0%2B5/ElectronJS-9.1.0+5-x86_64-linux-musl.tar.gz"
[[electronjs_app]]
arch = "aarch64"
git-tree-sha1 = "bf8267793953d41b83f2b9bfb4209fe2547b0e33"
libc = "musl"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "64460c3b41ed2426be55ffe233af8b9a230c2c83e4d3705ec74c0ead0aaa3006"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v9.1.0%2B5/ElectronJS-9.1.0+5-aarch64-linux-musl.tar.gz"
[[electronjs_app]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "54c760bb0118f54f54fbf7120d22057dbb179839"
libc = "musl"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "b60c94383705c1a05fca128284cfb77243ab2ac6542cc9cb72f913796fe75e02"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v9.1.0%2B5/ElectronJS-9.1.0+5-armv7l-linux-musleabihf.tar.gz"
[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "3ba739a4ed073587d96415faecef10a5ccea63ba"
os = "macos"

    [[electronjs_app.download]]
    sha256 = "36d9c885dfa0efe48fba148eec7894ca02da693166b2597a64bf647fb72e6d9e"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v9.1.0%2B5/ElectronJS-9.1.0+5-x86_64-apple-darwin14.tar.gz"
[[electronjs_app]]
arch = "i686"
git-tree-sha1 = "f2af79213ab4afedb13f302d350b8b6b89fa49b1"
os = "windows"

    [[electronjs_app.download]]
    sha256 = "562270250bc0c48c68bbc8c50e4ec3433730cab3be26eef52aa4bd76e1440181"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v9.1.0%2B5/ElectronJS-9.1.0+5-i686-w64-mingw32.tar.gz"
[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "ca0342e0bab6657b29b8c9153ccf8b6983ee0670"
os = "windows"

    [[electronjs_app.download]]
    sha256 = "11d0bf2883c4b3fa5abf57809ae00bbcc5b1d50b748a72d89b06020ed80c4cac"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v9.1.0%2B5/ElectronJS-9.1.0+5-x86_64-w64-mingw32.tar.gz"
