[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "786266ea382e52cb9b916dd144826e94729d5a69"
libc = "glibc"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "724795e4b97ad79697807cfb0f58e5cd713804e7427106250abc0d0935fdb97c"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v19.0.4%2B0/ElectronJS-19.0.4+0-x86_64-linux-gnu.tar.gz"
[[electronjs_app]]
arch = "aarch64"
git-tree-sha1 = "91d9a7f00e95da26cc3a75a9c29fc524071cf600"
libc = "glibc"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "115c63628608ca4078ddcef98c95c1a76be6a9c4807f200b8a63e0d6f5ab4719"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v19.0.4%2B0/ElectronJS-19.0.4+0-aarch64-linux-gnu.tar.gz"
[[electronjs_app]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a30084d6a2e1f00856601d3192d9ed7623b6a624"
libc = "glibc"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "683beab40162bcb3814986149264f483a042edb30a6451d5a9b3ab67d073735f"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v19.0.4%2B0/ElectronJS-19.0.4+0-armv7l-linux-gnueabihf.tar.gz"
[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "786266ea382e52cb9b916dd144826e94729d5a69"
libc = "musl"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "36a62067b1a23cb983210c93730ab42bfe99f6302450adb9882fd673d714d9ab"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v19.0.4%2B0/ElectronJS-19.0.4+0-x86_64-linux-musl.tar.gz"
[[electronjs_app]]
arch = "aarch64"
git-tree-sha1 = "91d9a7f00e95da26cc3a75a9c29fc524071cf600"
libc = "musl"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "3779d3986d8912d2bc369dcde119fa5ed8ad1508ac78b206793ee70c27d14d52"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v19.0.4%2B0/ElectronJS-19.0.4+0-aarch64-linux-musl.tar.gz"
[[electronjs_app]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a30084d6a2e1f00856601d3192d9ed7623b6a624"
libc = "musl"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "d4c4f9b724e14906a00b7daf1861c3c0ba552022313505171b3c0f716b4b2650"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v19.0.4%2B0/ElectronJS-19.0.4+0-armv7l-linux-musleabihf.tar.gz"
[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "7a9ac683a7092d064df9498f0da88ee625042b77"
os = "macos"

    [[electronjs_app.download]]
    sha256 = "41c0bfb8d1f165ccbac61a212d013ec4d2c90a5eb16877da7b16fc9f3abc748d"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v19.0.4%2B0/ElectronJS-19.0.4+0-x86_64-apple-darwin14.tar.gz"
[[electronjs_app]]
arch = "aarch64"
git-tree-sha1 = "b91d2dd029bdfd4a6954cf64c062b25550be1a29"
os = "macos"

    [[electronjs_app.download]]
    sha256 = "4c790eb1bdaaede1d306ff7be559973bed4de1fe9ca39bea21dbb40a12e6aeae"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v19.0.4%2B0/ElectronJS-19.0.4+0-aarch64-apple-darwin14.tar.gz"
[[electronjs_app]]
arch = "i686"
git-tree-sha1 = "fc9b3b5b99f8c2d491a55d623b4b3ebc058ee00e"
os = "windows"

    [[electronjs_app.download]]
    sha256 = "e4352412a5251bbc3a5e1eac3000f87bb1e24fcfe534c100c5106fb318cd20b0"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v19.0.4%2B0/ElectronJS-19.0.4+0-i686-w64-mingw32.tar.gz"
[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "c0a2184e2dbdb0dd8349ecfb768d68312cf2ff71"
os = "windows"

    [[electronjs_app.download]]
    sha256 = "841c31232494aa0896d6fd5586af62fdc3bf36fd03a01260fa43bb92be16f177"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v19.0.4%2B0/ElectronJS-19.0.4+0-x86_64-w64-mingw32.tar.gz"
