[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "8731693ea495ec92614ea8a5da62f8e66909f0c1"
libc = "glibc"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "d30cacd2953453818268fb1a213ae02c126661d030f053892926d3a97c22320a"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v9.1.0%2B1/ElectronJS-9.1.0+1-x86_64-linux-gnu.tar.gz"
[[electronjs_app]]
arch = "aarch64"
git-tree-sha1 = "bf8267793953d41b83f2b9bfb4209fe2547b0e33"
libc = "glibc"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "e81f2e87555d2d4b7549ba5651d10330d4a451195ad9b5aa14ce17fdc990271c"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v9.1.0%2B1/ElectronJS-9.1.0+1-aarch64-linux-gnu.tar.gz"
[[electronjs_app]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "54c760bb0118f54f54fbf7120d22057dbb179839"
libc = "glibc"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "c248fdd183a220df7037c1f3e4f5e69510f512358c380a01e1eba1d0de55c29c"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v9.1.0%2B1/ElectronJS-9.1.0+1-armv7l-linux-gnueabihf.tar.gz"
[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "8731693ea495ec92614ea8a5da62f8e66909f0c1"
libc = "musl"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "138ba241d1dcd0753f530e4361c7f22dc2fd3cd820e7d5e853bad5419716a9d7"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v9.1.0%2B1/ElectronJS-9.1.0+1-x86_64-linux-musl.tar.gz"
[[electronjs_app]]
arch = "aarch64"
git-tree-sha1 = "bf8267793953d41b83f2b9bfb4209fe2547b0e33"
libc = "musl"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "bbb26e4e79ec41d9a80a76e69bff2d46f726607bbfdc25d0bfd18c06f6f21839"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v9.1.0%2B1/ElectronJS-9.1.0+1-aarch64-linux-musl.tar.gz"
[[electronjs_app]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "54c760bb0118f54f54fbf7120d22057dbb179839"
libc = "musl"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "e25a5b48a7c23cdaed77ee8fab06a96f7843e7653834c426fb3ddc47cca4f754"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v9.1.0%2B1/ElectronJS-9.1.0+1-armv7l-linux-musleabihf.tar.gz"
[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "3ba739a4ed073587d96415faecef10a5ccea63ba"
os = "macos"

    [[electronjs_app.download]]
    sha256 = "3334ce29e72713d355c07ecb141668d25273d326c2ac0cd1399adc3b583d4151"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v9.1.0%2B1/ElectronJS-9.1.0+1-x86_64-apple-darwin14.tar.gz"
[[electronjs_app]]
arch = "i686"
git-tree-sha1 = "68dea0b5b5c3eb20ef83ded02f908f8b22e969e6"
os = "windows"

    [[electronjs_app.download]]
    sha256 = "10856ec797aef63eba22c847637d1cdcb4d00970da745c1e22ce266c38ae1bf5"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v9.1.0%2B1/ElectronJS-9.1.0+1-i686-w64-mingw32.tar.gz"
[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "5a1bce5ee5f832396865669b6716cae1a02c235f"
os = "windows"

    [[electronjs_app.download]]
    sha256 = "82438f1d02533fd8ccef9bb8b3c86561b67b2ee14ce06ca1fa0b2f87c767e406"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v9.1.0%2B1/ElectronJS-9.1.0+1-x86_64-w64-mingw32.tar.gz"
