[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "41afcbdbe95343621162214b9fc07813c12b5d36"
libc = "glibc"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "405da5f4914cfd63a02f01ce8e1e72d078208422cc752e39f06666c6bff86487"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v7.1.2%2B0/ElectronJS-7.1.2+0-x86_64-linux-gnu.tar.gz"
[[electronjs_app]]
arch = "aarch64"
git-tree-sha1 = "7f1cfc16fd19d077fef353b364f0edd5d18aa8ce"
libc = "glibc"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "d32f28485af706aa07bb02e3ec8cf908c8549e8b3fefdc962d656ac31571175b"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v7.1.2%2B0/ElectronJS-7.1.2+0-aarch64-linux-gnu.tar.gz"
[[electronjs_app]]
arch = "armv7l"
git-tree-sha1 = "fcc61e85a8bef71a539b796c8378d2fd559b1f82"
libc = "glibc"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "01d43e3c57dcec4f0351b01dbf31478afb8535c68d401887fd0c6328cdd69590"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v7.1.2%2B0/ElectronJS-7.1.2+0-arm-linux-gnueabihf.tar.gz"
[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "41afcbdbe95343621162214b9fc07813c12b5d36"
libc = "musl"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "be5dab01b4ba3339a3d87b29c2dc605b57c08ac2fd8eb36b0f06df937362b199"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v7.1.2%2B0/ElectronJS-7.1.2+0-x86_64-linux-musl.tar.gz"
[[electronjs_app]]
arch = "aarch64"
git-tree-sha1 = "7f1cfc16fd19d077fef353b364f0edd5d18aa8ce"
libc = "musl"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "13a4539c149c46f48d9640262b445a4610b19d5855ddd3b0149a1444bb647fed"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v7.1.2%2B0/ElectronJS-7.1.2+0-aarch64-linux-musl.tar.gz"
[[electronjs_app]]
arch = "armv7l"
git-tree-sha1 = "fcc61e85a8bef71a539b796c8378d2fd559b1f82"
libc = "musl"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "153005783c17214625132dd8eea1ea6a6e97a3bcc0efc256558ed84d74210bd1"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v7.1.2%2B0/ElectronJS-7.1.2+0-arm-linux-musleabihf.tar.gz"
[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "8dcb05674719648a37669520bc9a6ef8773032f2"
os = "macos"

    [[electronjs_app.download]]
    sha256 = "cd266dbeb049ddeb90147aadf090241dda0b45ea46d632feaf3b50af28ddee97"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v7.1.2%2B0/ElectronJS-7.1.2+0-x86_64-apple-darwin14.tar.gz"
[[electronjs_app]]
arch = "i686"
git-tree-sha1 = "0337e22522cfe87d096e392f35bf759c4fd0e2f2"
os = "windows"

    [[electronjs_app.download]]
    sha256 = "12a3b8c3d1eabd1af02786dae8d27b76eef3f04b517eddf88b6335eab77c8bbe"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v7.1.2%2B0/ElectronJS-7.1.2+0-i686-w64-mingw32.tar.gz"
[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "3cac82ef60c809398a5dd6870b5e97d42dbe2df1"
os = "windows"

    [[electronjs_app.download]]
    sha256 = "2abb775e36658b77adc809772d35d5f9c241679134f8d56031aaab9cfe926465"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v7.1.2%2B0/ElectronJS-7.1.2+0-x86_64-w64-mingw32.tar.gz"
