[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "cae80dc5ebd42950807d603cea93d970432b956d"
libc = "glibc"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "f6246a58bc73157e3c6049e6e52c8e3cdf5ed7d3894bc0f1f54159b1a0a26922"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v25.2.0%2B0/ElectronJS-25.2.0+0-x86_64-linux-gnu.tar.gz"
[[electronjs_app]]
arch = "aarch64"
git-tree-sha1 = "60212664bd4e4667045d6372e6345b87317de559"
libc = "glibc"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "7595401b1b2912c854c25eb341dfd2865072627a1022f17f3e7b496f9c0a162d"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v25.2.0%2B0/ElectronJS-25.2.0+0-aarch64-linux-gnu.tar.gz"
[[electronjs_app]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "58f917e9a4c1d3adf8d0414bc2c26402a3669b81"
libc = "glibc"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "4be38fce8a71d6d39ce02432f64ed45eff500f2f97731abde9f49ab09693a90b"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v25.2.0%2B0/ElectronJS-25.2.0+0-armv7l-linux-gnueabihf.tar.gz"
[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "cae80dc5ebd42950807d603cea93d970432b956d"
libc = "musl"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "ab1bb26418ca22ede6a4524a16f13b794d4837bf7c6d7510d2733c90d6fe59df"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v25.2.0%2B0/ElectronJS-25.2.0+0-x86_64-linux-musl.tar.gz"
[[electronjs_app]]
arch = "aarch64"
git-tree-sha1 = "60212664bd4e4667045d6372e6345b87317de559"
libc = "musl"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "f546b24e121118497761239a25e48f3811a221ef0545086f2bfd6d97078347ba"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v25.2.0%2B0/ElectronJS-25.2.0+0-aarch64-linux-musl.tar.gz"
[[electronjs_app]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "58f917e9a4c1d3adf8d0414bc2c26402a3669b81"
libc = "musl"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "24d185683859487083ebcfd5c7a57a2e7f7444ef6b3023d080ce0a783050d555"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v25.2.0%2B0/ElectronJS-25.2.0+0-armv7l-linux-musleabihf.tar.gz"
[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "122059e6ad151fa185380cae2d5689c32d042de8"
os = "macos"

    [[electronjs_app.download]]
    sha256 = "9067c07246f2c94de32f06f354dda28a2078a3fd42ee812ccd57f437a347b3b1"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v25.2.0%2B0/ElectronJS-25.2.0+0-x86_64-apple-darwin14.tar.gz"
[[electronjs_app]]
arch = "aarch64"
git-tree-sha1 = "28d75c9551b709f4f8172bf33e631b433c6c68d6"
os = "macos"

    [[electronjs_app.download]]
    sha256 = "456fa0b66f876fb3a4526889365671c0dc2cfc3f0057816dd53caed26dda6836"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v25.2.0%2B0/ElectronJS-25.2.0+0-aarch64-apple-darwin14.tar.gz"
[[electronjs_app]]
arch = "i686"
git-tree-sha1 = "feb6763f9bb7535de2f273aa4e6bc4d25a09862f"
os = "windows"

    [[electronjs_app.download]]
    sha256 = "f8eea6616223a127ff65c04928a5ee5f52db6d330c6369b2571bc9ca1090d664"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v25.2.0%2B0/ElectronJS-25.2.0+0-i686-w64-mingw32.tar.gz"
[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "397a0a9fb9e18e9c02b63a015adeadcaf37ff245"
os = "windows"

    [[electronjs_app.download]]
    sha256 = "363b88e53af6d15a265824bb0be4d6b4cf57bfc87533c4cd4c18699018207cdd"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v25.2.0%2B0/ElectronJS-25.2.0+0-x86_64-w64-mingw32.tar.gz"
