[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "8731693ea495ec92614ea8a5da62f8e66909f0c1"
libc = "glibc"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "8035309d4ff6c9ffa149eb080c40931a0d46714f6bd249b77db266b6f31a21b9"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v9.1.0%2B0/ElectronJS-9.1.0+0-x86_64-linux-gnu.tar.gz"
[[electronjs_app]]
arch = "aarch64"
git-tree-sha1 = "bf8267793953d41b83f2b9bfb4209fe2547b0e33"
libc = "glibc"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "7da7f2f74b1c5bfa56a2c818a1739a89967d04e864d2ff058a878bb7875826de"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v9.1.0%2B0/ElectronJS-9.1.0+0-aarch64-linux-gnu.tar.gz"
[[electronjs_app]]
arch = "armv7l"
git-tree-sha1 = "54c760bb0118f54f54fbf7120d22057dbb179839"
libc = "glibc"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "03ce1f68c38b20f800da2e270d45e92ffd4ed3ea2451dcbb7b7340d4d79d2200"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v9.1.0%2B0/ElectronJS-9.1.0+0-arm-linux-gnueabihf.tar.gz"
[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "8731693ea495ec92614ea8a5da62f8e66909f0c1"
libc = "musl"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "5aaaf2e5d77908cb0daac71849c2e9c455d28e0f041257aa16840e8c0d1ae283"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v9.1.0%2B0/ElectronJS-9.1.0+0-x86_64-linux-musl.tar.gz"
[[electronjs_app]]
arch = "aarch64"
git-tree-sha1 = "bf8267793953d41b83f2b9bfb4209fe2547b0e33"
libc = "musl"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "10c1a7f443d8ab1ec4c4c537d0ed94800093ce43af4f5cb0158ab01f8e2ee633"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v9.1.0%2B0/ElectronJS-9.1.0+0-aarch64-linux-musl.tar.gz"
[[electronjs_app]]
arch = "armv7l"
git-tree-sha1 = "54c760bb0118f54f54fbf7120d22057dbb179839"
libc = "musl"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "fe33a650fd5fe60ae2f6bb460f2343adfe6a7bc63c1279e4610ef62bb1a06bb0"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v9.1.0%2B0/ElectronJS-9.1.0+0-arm-linux-musleabihf.tar.gz"
[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "3ba739a4ed073587d96415faecef10a5ccea63ba"
os = "macos"

    [[electronjs_app.download]]
    sha256 = "6a2c6a2f867fbe7abf64d19e68ddd1ea85b46c1d03704e8ad397232b578b87f8"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v9.1.0%2B0/ElectronJS-9.1.0+0-x86_64-apple-darwin14.tar.gz"
[[electronjs_app]]
arch = "i686"
git-tree-sha1 = "06a003964ce44ea8706506c3a067ac3c29b5b2d9"
os = "windows"

    [[electronjs_app.download]]
    sha256 = "4b6c51166334a0d7715297f1b9acf57f2acfdd52993d371525a805cd831f80ea"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v9.1.0%2B0/ElectronJS-9.1.0+0-i686-w64-mingw32.tar.gz"
[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "aaa4041dbb1e073d9d1491a285929d6ce1b0e46a"
os = "windows"

    [[electronjs_app.download]]
    sha256 = "df2c968ae76f1c4e37b554157d6a0a8a631da3629d2073eb628209e7b66eaaf5"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v9.1.0%2B0/ElectronJS-9.1.0+0-x86_64-w64-mingw32.tar.gz"
